apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apple
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://raw.githubusercontent.com/hieuldt/quick_lab/main/charts'
    chart: http-echo
    targetRevision: 0.1.0
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
