apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actions-runner-controller
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: actions-runner-controller
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    path: actions-runner-controller
    repoURL: https://github.com/alrajhi-my/k8s-apps-platform
    targetRevision: HEAD
    helm:
      releaseName: actions-runner-controller
      valueFiles:
        - values-{{ $.Values.env }}.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
