apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: external-dns
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    path: external-dns
    repoURL: https://github.com/hieuldt/quick_lab
    targetRevision: HEAD
    helm:
      releaseName: external-dns
      valueFiles:
        - values-{{ $.Values.env }}.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
