apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    path: ingress-nginx
    repoURL: https://github.com/hieuldt/quick_lab
    targetRevision: HEAD
    helm:
      releaseName: ingress-nginx
      valueFiles:
        - values-sandbox.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
