apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
spec:
  destination:
    namespace: 
    server: https://kubernetes.default.svc
  project: pod7-training
  source:
    path: nginx-ingress
    repoURL: https://github.com/hieuldt/quick_lab.git
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true