apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opendistro
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://raw.githubusercontent.com/hieuldt/quick_lab/main/charts'
    chart: opendistro-es
    targetRevision: 1.13.2
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
