apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: react-app-2
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: charts/example-chart
    repoURL: https://github.com/anais-codefresh/react-article-display.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true