apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apple-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: bitnami/nginx-ingress-controller
    repoURL: https://github.com/hieuldt/quick_lab.git
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true