apiVersion: v2
name: external-dns
description: ExternalDNS synchronizes exposed Kubernetes Services and Ingresses with DNS providers.
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: external-dns
    version: 1.6.0
