external-dns:
  serviceAccount:
    create: false
    name: kubernetes_service_account.external_dns.metadata.0.name
  rbac:
    create: false
  provider: aws
  policy: sync
  domainFilters: "arbmtest.local"
  txtOwnerId: "arbmtest.local"
  aws.zoneType: private
