external-dns:
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::550374772193:role/system-external-dns-role
  policy: sync

  domainFilters:
    - hieuldt.com
    - arbmtest.local

########################
# serviceAccount:
#   create: false
#   name: kubernetes_service_account.external_dns.metadata.0.name
# rbac:
#   create: false
# provider: aws
# policy: sync
# sources:
#   - service
#   - ingress
# domainFilters: "{${join(",", "arbmtest.local")}}"
# txtOwnerId: "arbmtest.local"
# aws.zoneType: private
