kibana:
  ingress:
    enabled: true
    annotations: {
     kubernetes.io/ingress.class: nginx,
     kubernetes.io/tls-acme: "true"
    }
    path: /
    hosts:
      - opendistro.nonprod.pod7.huyy
    tls: 
     - secretName: letsencrypt-staging
       hosts:
          - opendistro.nonprod.pod7.huyy
elasticsearch:
  master:
    replicas: 2
    persistence:
      storageClass: "gp2"
      accessModes:
        - ReadWriteOnce
      size: 8Gi
  data:
    replicas: 3
    persistence:
      storageClass: "gp2"
      accessModes:
        - ReadWriteOnce
      size: 8Gi
  client:
    replicas: 2
