kibana:
  ingress:
    enabled: true
    annotations: {
     kubernetes.io/ingress.class: nginx,
     kubernetes.io/tls-acme: "true"
    }
    path: /
    hosts:
      - opendistro.prod.pod7.huyy
    tls: 
     - secretName: letsencrypt-staging
       hosts:
          - opendistro.prod.pod7.huyy
elasticsearch:
  master:
    persistence:
      storageClass: "gp2"
      accessModes:
        - ReadWriteOnce
      size: 8Gi
  data:
    persistence:
      storageClass: "gp2"
      accessModes:
        - ReadWriteOnce
      size: 8Gi